name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d%H%M')"
    - name: Say current date
      run: echo "${{ steps.date.outputs.date }}"
    - name: Restore dependencies
      run: dotnet restore
      working-directory: /Source/Monorepo.DependencyManager/Monorepo.DependencyManager/
    - name: Build
      run: dotnet build --no-restore
      #working-directory: Source/Monorepo.DependencyManager/Monorepo.DependencyManager/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      #working-directory: Source/Monorepo.DependencyManager/Monorepo.DependencyManager/
    - name: Pack
      run: dotnet pack -c Release -p:PackageVersion=${{ steps.date.outputs.date }}
      #working-directory: Source/Monorepo.DependencyManager/Monorepo.DependencyManager/
    - name: push
      run:  dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      #working-directory: Source/Monorepo.DependencyManager/Monorepo.DependencyManager/
